### ISSUE TITLE
Can't open tcp/445

### ISSUE THREAD

**Issue by trentwiles** [omaemae/portfucker#1]
I'm using this and I can't see to open up port 445. I've tweaked the code so it opens 445:
```
addr = ('0.0.0.0', 445)
```

But when I run it and try to open port 445 myself, the port is still filtered. What could be causing this? I am root and have not firewalled port 445.

**Comment by itsvic-dev** [comment]
i have no idea, does the script throw any errors? do you have any firewall which may be blocking port 445?

**Comment by trentwiles** [comment]
Got it working, weird, must be something with socketserver. Anyway, cool project!

**Comment by itsvic-dev** [comment]
> Got it working, weird, must be something with socketserver. Anyway, cool project!

thanks! glad you got it working :)
